// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjtcrjtjfqknkycftwxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdGNyanRqZnFrbmt5Y2Z0d3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjAyMDksImV4cCI6MjA2Mjk5NjIwOX0.tJkQe3FbdOROEa5Mf9w4Rll0itypYUANCL6hjKPnQGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);